- name: Recopilar informacion del sistema y generar CSV
  hosts: all
  gather_facts: true
  vars:
    ansible_shell_type: powershell
    ansible_remote_tmp: 'C:\Temp'
  tasks:
    - name: Mostrar informacion recolectada con ID
      ansible.builtin.debug:
        msg: >
          Hostname: {{ ansible_hostname }} |
          ID Equipo: {{ ansible_product_serial | default('N/A') }} |
          Usuario: {{ ansible_user_id | default('N/A') }} |
          IP: {{ ansible_host }} |
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}

    - name: Generar registro en formato CSV en el workspace seguro
      delegate_to: localhost
      connection: local
      vars:
        ansible_shell_type: sh
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/inventario.csv"
        line: "{{ ansible_hostname }},{{ ansible_product_serial | default('N/A') }},{{ ansible_user_id | default('N/A') }},{{ ansible_host }},{{ ansible_distribution }} {{ ansible_distribution_version }}"
        create: yes
        insertafter: EOF

    - name: Mostrar contenido del archivo CSV generado
      delegate_to: localhost
      connection: local
      vars:
        ansible_shell_type: sh
      ansible.builtin.command: cat "{{ playbook_dir }}/inventario.csv"
      register: csv_output

    - name: Imprimir CSV en consola de AWX
      ansible.builtin.debug:
        var: csv_output.stdout_lines
